services:
  # MyEncrypt ACME Server
  myencrypt:
    build: .
    ports:
      - "14000:80"  # Host port 14000 maps to container port 80
    environment:
      - MYENCRYPT_EXPOSE_PORT=14000  # Required: Host-accessible port
      - MYENCRYPT_PROJECT_NAME=myencrypt  # Required: Project name for Docker mode
      - MYENCRYPT_INDIVIDUAL_CERT_TTL=168h  # 7 days (7 * 24h)
      - MYENCRYPT_CA_CERT_TTL=19200h
      - MYENCRYPT_ALLOWED_DOMAINS=localhost,*.localhost,*.test,*.example,*.invalid,app-traefik.localhost,app-certbot.localhost
      - MYENCRYPT_CERT_STORE_PATH=/data
      - MYENCRYPT_DATABASE_PATH=/data/myencrypt.db
      - MYENCRYPT_LOG_LEVEL=debug  # Enable debug logging
    volumes:
      - myencrypt_data:/data  # Only MyEncrypt data needs persistence
    healthcheck:
      test: ["/bin/myencrypt", "healthcheck"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    restart: unless-stopped

  # Demo App 1: Autocert (direct HTTPS)
  autocert.localhost:
    build:
      context: ./examples/autocert-app
      dockerfile: Dockerfile
    ports:
      - "8443:443"  # Map host port 8443 to container port 443 for TLS-ALPN challenge
    environment:
      - DOMAIN=autocert.localhost
      - PORT=443    # Use standard HTTPS port for TLS-ALPN challenge
      - ACME_DIRECTORY_URL=http://myencrypt:80/acme/directory
      - CACHE_DIR=/tmp/autocert-cache  # Use temporary directory, no persistence needed
    depends_on:
      - myencrypt
    restart: unless-stopped
    # No volumes - certificates will be fetched fresh each time

  # Shared Simple HTTP App (used by both Caddy and Traefik)
  simple-http-app:
    build:
      context: ./examples/simple-http-app
      dockerfile: Dockerfile
    environment:
      - APP_NAME=Shared HTTP App
      - PORT=80
    restart: unless-stopped
    labels:
      # Traefik labels for this shared app
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app-traefik.localhost`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=80"
      - "traefik.docker.network=myencrypt2_default"

  # Traefik Reverse Proxy (alternative to Caddy)
  traefik.localhost:
    image: traefik:v3.0
    ports:
      - "8081:80"    # HTTP (different port to avoid conflict with Caddy)
      - "8444:443"   # HTTPS (different port to avoid conflict with Caddy)
      - "8082:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./examples/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./examples/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      # No data volume - certificates will be fetched fresh each time
    depends_on:
      - myencrypt
      - simple-http-app
    restart: unless-stopped
    networks:
      default:
        aliases:
          - app-traefik.localhost  # Allow MyEncrypt to resolve this hostname
    labels:
      # Traefik dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=myencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.docker.network=myencrypt2_default"

  # Certbot + Nginx Example
  app-certbot.localhost:
    build:
      context: ./examples/certbot-nginx
      dockerfile: Dockerfile
    ports:
      - "8085:80"    # HTTP (different port to avoid conflicts)
      - "8446:443"   # HTTPS (different port to avoid conflicts)
    # No volumes - certificates and logs will be fresh each time
    depends_on:
      - myencrypt
      - simple-http-app
    restart: unless-stopped
    labels:
      # Traefik labels (if needed for integration)
      - "traefik.enable=false"  # Disable Traefik for this service

volumes:
  myencrypt_data:  # Only MyEncrypt CA and database need persistence

networks:
  default:
    name: myencrypt2_default
