name: Go Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Build for Linux (amd64)
        run: |
          GOOS=linux GOARCH=amd64 go install -ldflags="-s -w" github.com/shibukawa/myencrypt/cmd/myencrypt@latest
          mv /home/runner/go/bin/myencrypt myencrypt-linux-amd64
      - name: Upload Linux (amd64) binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./myencrypt-linux-amd64
          asset_name: myencrypt-linux-amd64
          asset_content_type: application/octet-stream 

      - name: Build for Windows (amd64)
        run: |
          GOOS=windows GOARCH=amd64 go install -trimpath -ldflags="-s -w" github.com/shibukawa/myencrypt/cmd/myencrypt@latest
          mv /home/runner/go/bin/windows_amd64/myencrypt.exe myencrypt-windows-amd64.exe
      - name: Upload Windows (amd64) binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./myencrypt-windows-amd64.exe
          asset_name: myencrypt-windows-amd64.exe
          asset_content_type: application/octet-stream 

      - name: Build for macOS (arm64)
        run: |
          GOOS=darwin GOARCH=arm64 go install -trimpath -ldflags="-s -w" github.com/shibukawa/myencrypt/cmd/myencrypt@latest
          mv /home/runner/go/bin/darwin_arm64/myencrypt myencrypt-darwin-arm64
      - name: Upload macOS (arm64) binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./myencrypt-darwin-arm64
          asset_name: myencrypt-darwin-arm64
          asset_content_type: application/octet-stream 