name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Run tests
      run: go test -timeout 5m ./...

  docker-build-test:
    name: Build Docker Images
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04-arm
            platform: linux/arm64
            platform_pair: linux-arm64
          - os: ubuntu-latest
            platform: linux/amd64
            platform_pair: linux-amd64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ matrix.platform }}
        push: false
        outputs: type=image,push-by-digest=true,name-canonical=true
        build-args: |
          VERSION=${{ github.ref_name }}

    - name: Export digest
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"
